from common import *

SITUACAO = 'SITUACAO'
ORGAO_EXERCICIO = 'ORGAO_EXERCICIO'
ORGAO_ORIGEM = 'ORGAO_ORIGEM'

NOME_CAMPOS = [
    NOME, 
    CARGO, 
    ORGAO_EXERCICIO,
    ORGAO_ORIGEM,
    REMUNERACAO_MES
    ]