from enum import Enum


class PortalParamsEnum(Enum):
    #(param_sc, param_se, param_sp)
    POLICIA_MILITAR = ('POLICIA MILITAR', 20, 57)
    SECRETARIA_SEGURANCA = ('SECRETARIA DE ESTADO DA SEGURANCA PUBLICA', 18, 78)
    SECRETARIA_EDUCACAO = ('SECRETARIA DO ESTADO DA EDUCACAO', 217, 67)
    DEPARTAMENTO_TRANSITO = ('DEPARTAMENTO ESTADUAL DE TRANSITO', 19, 21)
