from src.constants.common import *

FERIAS_E_13_SALARIO = 'FERIAS_E_13_SALARIO'
PAGAMENTOS_EVENTUAIS = 'PAGAMENTOS_EVENTUAIS'
LICENCA_PREMIO_INDENIZADA = 'LICENCA_PREMIO_INDENIZADA'
ABONO_PERMANENCIA_E_OUTRAS_INDENIZACOES = 'ABONO_PERMANENCIA_E_OUTRAS_INDENIZACOES'
REDUTOR_SALARIAL = 'REDUTOR_SALARIAL'
TOTAL_LIQUIDO = 'TOTAL_LIQUIDO'

NOME_CAMPOS_SP = [
    NOME,
    ORGAO,
    CARGO,
    REMUNERACAO_MES,
    FERIAS_E_13_SALARIO,
    PAGAMENTOS_EVENTUAIS,
    LICENCA_PREMIO_INDENIZADA,
    ABONO_PERMANENCIA_E_OUTRAS_INDENIZACOES,
    REDUTOR_SALARIAL, TOTAL_LIQUIDO
]