from enum import Enum

from src.constants.dicionarios_normalizacao import *


class PortalParamsEnum(Enum):
    #(param_sc, param_se, param_sp)
    POLICIA_MILITAR = ('POLICIA MILITAR', 20, 57, POLICIA_MILITAR_CARGOS)
    SECRETARIA_SEGURANCA = ('SECRETARIA DE ESTADO DA SEGURANCA PUBLICA', 18, 78, SECRETARIA_SEGURANCA_CARGOS)
    SECRETARIA_EDUCACAO = ('SECRETARIA DO ESTADO DA EDUCACAO', 217, 67, SECRETARIA_EDUCACAO_CARGOS)
    DEPARTAMENTO_TRANSITO = ('DEPARTAMENTO ESTADUAL DE TRANSITO', 19, 21, DEPARTAMENTO_TRANSITO_CARGOS)
