import requests
import re
from bs4 import BeautifulSoup

from src.constants.html_tags import *
from src.requester.requester import Requester


class SpRequester(Requester):
    URL = 'http://www.transparencia.sp.gov.br/PortalTransparencia-Report/Remuneracao.aspx'
    PAGE_SCRIPT_MANAGER = 'ScriptManager1|btnExibirRelatorio'
    VIEWSTATE = '/wEPDwULLTE4NjgwMjEwODMPZBYCAgMPZBYMAgUPEA8WBh4ORGF0YVZhbHVlRmllbGQFCE9SR0FPX0lEHg1EYXRhVGV4dEZpZWxkBQpPUkdBT19ERVNDHgtfIURhdGFCb3VuZGdkEBVRBVRPRE9THUFETUlOSVNUUkFDQU8gR0VSQUwgRE8gRVNUQURPHUFHLk0uVi5QQVIuTElULk5PUlRFIEFHRU1WQUxFHEFHLk1FVC5TT1JPQ0FCQSBBR0VNU09ST0NBQkEdQUcuUkVHLlNFUlYuUFVCLkVTVC5TUCBBUlNFU1AeQUcuUkVHLlNWLlAuREVMLlRSLkUuU1AgQVJURVNQHUFHRU5DSUEgTUVULkNBTVBJTkFTIEFHRU1DQU1QHkFHRU5DSUEgTUVUUk9QLkIuU0FOVElTVEEgQUdFTR5DLkUuRUQuVEVDLlBBVUxBIFNPVVpBLUNFRVRFUFMdQy5QLlRSRU5TIE1FVFJPUE9MSVRBTk9TLUNQVE0dQ0FJWEEgQkVORUZJQy5QT0xJQ0lBIE1JTElUQVIKQ0FTQSBDSVZJTB1DRVRFU0ItQ0lBLkFNQklFTlRBTCBFU1QuUy5QLh1DSUEuREVTLkhBQi5VUkIuRVNULlMuUC4tQ0RIVR5DSUEuUEFVTElTLlNFQ1VSSVRJWkFDQU8gQ1BTRUMaQ0lBLlBBVUxJU1RBIFBBUkNFUklBUyBDUFAeQ0lBLlBST0MuREFET1MgRVNULlMuUC1QUk9ERVNQHkNPTS5TQU4uQkFTLkVTVC5TLlBBVUxPIFNBQkVTUB1DT01QLk1FVFJPUE9MSVRBTk8gUy5QLi1NRVRSTx1DT01QQU5ISUEgRE9DQVMgU0FPIFNFQkFTVElBTwVEQUVTUB1ERVBBUlRBTS5FU1RSQURBUyBST0RBR0VNIERFUh5ERVBUTy4gRVNULiBUUkFOU0lUTyBERVRSQU4gU1AeREVQVE8uQUdVQVMgRU5FUi5FTEVUUklDQSBEQUVFHkRFU0VOVk9MVi5ST0RPVklBUklPIFMvQS1ERVJTQR5ERVNFTlZPTFZFIFNQIEFHLkZPTS5FLlMuUEFVTE8eRU1BRSBFTVAuTUVULkFHVUFTIEVORVJHSUEgUy9BHkVNUC5NRVRSLlRSLlVSQi5TUC5TL0EtRU1UVS1TUBpGQUMuTUVELlMuSi5SLlBSRVRPLUZBTUVSUBtGQUMuTUVESUNJTkEgTUFSSUxJQS1GQU1FTUEaRklURVNQLUpPU0UgR09NRVMgREEgU0lMVkEeRlVORC5BTVBBUk8gUEVTUS5FU1QuU1AtRkFQRVNQHkZVTkQuQ09OUy5QUi5GTE9SLkVTVC5TUCBGLkZMLhxGVU5ELk1FTU9SSUFMIEFNRVJJQ0EgTEFUSU5BHkZVTkQuUEUuQU5DSElFVEEtQy5QLlJBRElPIFRWLh1GVU5ELlBGLkRSLk0uUC5QSU1FTlRFTC1GVU5BUB5GVU5ELlBSRVYuQ09NUEwuRVNULlNQIFBSRVZDT00eRlVORC5QUk8tU0FOR1VFLUhFTU9DRU5UUk8gUy5QHEZVTkQuUkVNLlBPUC4iQy5ULkxJTUEiLUZVUlAeRlVORC5TSVNULkVTVC5BTkFMLkRBRE9TIFNFQURFHkZVTkQuVU4uVklSVFVBTCBFU1QuU1AgVU5JVkVTUBFGVU5EQUNBTyBDQVNBLVNQLhxGVU5EQUNBTyBERVNFTlYuRURVQ0FDQU8tRkRFHUZVTkRBQ0FPIE9OQ09DRU5UUk8gU0FPIFBBVUxPHkZVTkRBQ0FPIFBBUlFVRSBaT09MT0dJQ08gREUgUw9GVU5EQUNBTyBQUk9DT04WR0FCSU5FVEUgRE8gR09WRVJOQURPUhpILkMuRkFDLk1FRC5CT1RVQ0FUVS1IQ0ZNQh1IQyBGQUMgTUVESUNJTkEgUklCIFBSRVRPIFVTUBlIT1NQLkNMSU4uRkFDLk1FRC5NQVJJTElBHUhPU1AuQ0xJTi5GQUMuTUVELlVTUC1IQ0ZNVVNQHklOU1QgTUVEIFNPQyBDUklNSU5PIFNQLSBJTUVTQx5JTlNULkFTLk1FRC5TRVIuUFVCLkVTVCBJQU1TUEUeSU5TVC5QQUdUT1MuRVNQRUNJQUlTIFNQLUlQRVNQHklOU1QuUEVTT1MgTUVESUQuRS5TLlAtSVBFTS9TUB5JTlNULlBFU1EuVEVDTk9MT0dJQ0FTIEVTVC5TLlAdSlVOVEEgQ09NRVJDLkUuUy5QQVVMTy1KVUNFU1AZUE9MSUNJQSBNSUxJVEFSIFNBTyBQQVVMTxxQUk9DVVJBRE9SSUEgR0VSQUwgRE8gRVNUQURPHlNBTyBQQVVMTyBQUkVWSURFTkNJQSAgIFNQUFJFVh5TRUMuVFJBTlNQT1JURVMgTUVUUk9QT0xJVEFOT1MeU0VDUi5BR1JJQ1VMVFVSQSBBQkFTVEVDSU1FTlRPHlNFQ1IuQ1VMVFVSQSBFQ09OT01JQSBDUklBVElWQR5TRUNSLkRFU0VOVk9MVklNRU5UTyBFQ09OT01JQ08eU0VDUi5FU1QuRElSLlBFUy5DL0RFRklDSUVOQ0lBHFNFQ1JFVC4gRkFaRU5EQSBQTEFORUpBTUVOVE8eU0VDUkVULkFETUlOSVNUUi5QRU5JVEVOQ0lBUklBFlNFQ1JFVEFSSUEgREEgRURVQ0FDQU8XU0VDUkVUQVJJQSBEQSBIQUJJVEFDQU8TU0VDUkVUQVJJQSBEQSBTQVVERR1TRUNSRVRBUklBIERFIERFU0VOVk9MVklNRU5UTxZTRUNSRVRBUklBIERFIEVTUE9SVEVTFVNFQ1JFVEFSSUEgREUgR09WRVJOTxtTRUNSRVRBUklBIERFU0VOVi4gUkVHSU9OQUwdU0VDUkVUQVJJQSBJTkYuIE1FSU8gQU1CSUVOVEUeU0VDUkVUQVJJQSBKVVNUSUNBIEUgQ0lEQURBTklBHlNFQ1JFVEFSSUEgTE9HSVNULiBUUkFOU1BPUlRFUx1TRUNSRVRBUklBIE9SQ0FNRU5UTyBFIEdFU1RBTxxTRUNSRVRBUklBIFNFR1VSQU5DQSBQVUJMSUNBHFNFQ1JFVEFSSUEgVFVSSVNNTyBFIFZJQUdFTlMdU1VQRVJJTlQuQ09OVFIuRU5ERU1JQVMtU1VDRU4VUQItMQExATIBMwE0ATUBNgE3ATgBOQIxMAIxMQIxMgIxMwIxNAIxNQIxNgIxNwIxOAIxOQIyMAIyMQIyMgIyMwIyNAIyNQIyNgIyNwIyOAIyOQIzMAIzMQIzMgIzMwIzNAIzNQIzNgIzNwIzOAIzOQI0MAI0MQI0MgI0MwI0NAI0NQI0NgI0NwI0OAI0OQI1MAI1MQI1MgI1MwI1NAI1NQI1NgI1NwI1OAI1OQI2MAI2MQI2MgI2MwI2NAI2NQI2NgI2NwI2OAI2OQI3MAI3MQI3MgI3MwI3NAI3NQI3NgI3NwI3OAI3OQI4MBQrA1FnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2cWAWZkAgcPEGQQFQEFVE9ET1MVAQItMRQrAwFnFgFmZAIJDxAPFgYfAAULU0lUVUFDQU9fSUQfAQUNU0lUVUFDQU9fREVTQx8CZ2QQFQQFVE9ET1MLQVBPU0VOVEFET1MGQVRJVk9TDFBFTlNJT05JU1RBUxUEAi0xATEBMgEzFCsDBGdnZ2cWAWZkAgsPD2QWAh4Kb25LZXlQcmVzcwUncmV0dXJuIE1hc2NhcmFNb2VkYSh0aGlzLCcuJywnLCcsZXZlbnQpZAINDw9kFgIfAwUncmV0dXJuIE1hc2NhcmFNb2VkYSh0aGlzLCcuJywnLCcsZXZlbnQpZAIVD2QWAmYPZBYEAgEPFgIeB1Zpc2libGVoZAIDDw8WAh8EaGQWAgIDDzwrABECARAWABYAFgAMFCsAAGQYAgUeX19Db250cm9sc1JlcXVpcmVQb3N0QmFja0tleV9fFgQFDGltZ0V4cG9ydFR4dAUMSW1hZ2VCdXR0b24xBQxJbWFnZUJ1dHRvbjIFDEltYWdlQnV0dG9uMwUEZ3JpZA9nZBwDnANbYPhBn+riAHftvziSB3nVGSByM+XnTyV9zztR'
    EVENTVALIDATION = '/wEdAGeFoA4cpm3hg7I47SKrk1MMha8fMqpdVfgdiIcywQp19AS0oC9+kRn5wokBQj+YmSdj/RE4/VY2xVooDbyNylWSFXsupcqZ9EYohXUHrvyuvszqcPgWZLCNPbx1As5K6XI8YfiXwzc6jdd6doCEWNMhfUq2YkY3rbVwieJI30sGRBiYwU43rbtypsxax6Lexvr9tn/ppXosAOoaLiPglbLZDQ4AHCggkRiV1y9R5Jk3hxzIBiDVeBd4ex/DPERS7Y3hxS83fVJEzO6I+sKPdRPTZbKZKzZ/iI/o2LERffiPWbY0qpjFHBt23vPUuehVkAOA1ngNB93rbK+u0E54XcLAmWLN/l+z5m0ApRDNS4L3FwTfILDr1aT4Crd1/2X2tGTSlHv5v4gI+/4UxQdVOOXcJIWT3hhEHPLkfTczdhS+JPFzCLQyhLlM/TIkVLdCEWiXz8XDG1+qV0wHjm1sFCkHt5aLy6yjxTyv1FFML9B/o0JBJO+y+74vfDQlvwQWQHtswD+jri2Ja0FbYTVaHetzL3nIpMtKnzHrJejZWNnngPadPS2744kvbqzTJQaAdqOeYy/XyO581zGaQB16a5HkpT5jddxT22MOtOJS9+OuUHRXp8dj268DwFDqeWohT0vm1b0FOlCVjyi8V9MKHPYPpHgZ/2GzcT5zaEXX3Wa7dGMCaXmo3KMrfSTIEMtzpixzPEyfillVBjlMq8fiaJmavKW63uZc65AHMJEgzJBWOOnY33pftn93IOwZzZWV8DBA7v/9aPpqFJWx65SrmQqSjTKR9Q8znWzwmOcZE4/SuTP7i+Xb7NoOWr4anBMJ9L8iQIpPyUdRVhTh0dqpW9mg677VkTJzeFDr78YgZsAwP/X+dTV/INjSEi5I3GKGi7myZ7+jeKd7PDtAjn8O4hLTJfL4LFg4Nvwdmd/53R8Jw4b9e/lLobx4zXIq3GAuywAjOQvHY8AEnfNd/lXdKYxyzc/wfpCNJupjNVpUse2VJD4oS1BuBPCBdQ5aaErF4JFlItPtLQCYFzs0jfHra3vGXa5DUmVxUHX61STePVHIx+b2IzWzaVJbMWnr0ySeyyy/Z1AEi/GyAY4VRi7gupaG4KIpRnL0PqiHkB0m+FOAGOzlYyAzkRO1hwDnOQf3fkyzTk8GPsW4ORs6zPd+eDosaOUhW1MEtWA+SqsohtmqkoKbjumKVbQvus3TM3adBbzpeRPEjnLNywu7OwRAhFtyU0gmtXU9am1kuUbvzTaW93G/XW5pJhxIEGLJ46ijUCocW5ypp1AUfwUVaLtxxktia9eKFUCg16rKs9CfE8mQS1sJL8sXrl1kCYgl357rWaG95jfZ509s+m2fA+Ot0aP8OyaOU4R1ht8FAaoUaukJi9ac+52YAhiIATqgCuAVAUaz6iVZ30v9i3l79pG/QjT0yzItrPhgpeaj5FDDRNwFWQfE5v7dhuWXa0fqNuT0/3rHd8yAI/R31smXtVMpuDg4uNPHIl+2FxKOozxg/v++E9d/ZoPPgEhC0wqwEcy5cuqQMsS7I2iwe1Xfp9TBV2uBNFpR3V1ws1NcSb0O892YPaDPsxrja2GQM7SzAShZDNlCOSW7Tt/u0g+eirEQ/lwLvd/yO3h/PXkp4oZAfoeCSWuKxs7UkSXX7piPjdZRkxS8+1Tv52TtsW//arETeAIdqgWD21SCG/+SG/yFJtRwUalOOSCKwgXmjHLagrrOpyOVvrzcda9t4I8AvfZJNBX4HCyHl/8v7zlaXsN6v3xdx7SBYcgTu1GewkDpUJSUGbgYwhIf9Mpv89HGtvAZMRkXfH3bbC9O8Uq67E1QkUHv1Tdk/EvCzmIhrMiV57TNXcidZhg8/bokhrlHQSbw5Fv7+hQOUkpx2/o2hZX/la0LJERrZHGR7lm6QuZPvGJaKe/yOvBucDPUBRoybzEqxzgbp01a7aMeuABo0WWY4tkh4bQ5OzI+GH7/RZB05MAP3MBuVzHpW8wR7jevaD2wafvls7tlbqdnuEYGMpSpIfhLtDLmeBH+J24h93MPSg2A07rOVmaDH49Ud+nG8b7WVcFkEsB7onJj3/BjePr4wa6u7GfkxfSOw97IFcrjTUrCOXyDgpsnrLcmeVjClUUT7FoC6ZACrx5RZnllKSerU+IuKmLNV+2mZgnOAlNG5DVTg1vmrIx4Wzwbb1QZEjNCy6X4NJpPBRamMULum3+DY/vg2nDhz+oG+TZ0QB29ez0AFlg='
    STARTED = False

    def __init__(self, orgao: int = -1, cargo: int = -1, situacao: int = -1):
        self.orgao = orgao
        self.cargo = cargo
        self.situacao = situacao
        self.hdInicio = -1
        self.hdFinal = -1
        self.hdPaginalAtual = 0
        self.hdTotal = -1
        self.txtPagina = 0
        # inicializa o requester
        self.get_next()
        self.PAGE_SCRIPT_MANAGER = 'uppPanel|btnProximo'
        self.STARTED = True

    def get_next(self) -> None:
        self.get_html()
        bsoup = BeautifulSoup(self.PAGE, 'html.parser')
        self.hdInicio = int(bsoup.find(INPUT, attrs={'id': "hdInicio"}).get('value'))
        self.hdFinal = int(bsoup.find(INPUT, attrs={'id': "hdFinal"}).get('value'))
        self.hdPaginalAtual = int(bsoup.find(INPUT, attrs={'id': "hdPaginaAtual"}).get('value'))
        self.hdTotal = int(bsoup.find(INPUT, attrs={'id': "hdTotal"}).get('value'))
        self.VIEWSTATE = re.search(r'\|__VIEWSTATE\|(.*?)\|', self.PAGE).group(1)
        self.EVENTVALIDATION = re.search(r'\|__EVENTVALIDATION\|(.*?)\|', self.PAGE).group(1)
        self.txtPagina += 1

    def get_html(self) -> None:
        parameters = {
            'ScriptManager1': self.PAGE_SCRIPT_MANAGER,
            '__EVENTTARGET': '',
            '__EVENTARGUMENT': '',
            '__LASTFOCUS': '',
            '__VIEWSTATE': self.VIEWSTATE,
            '__VIEWSTATEGENERATOR': 'E42B1F40',
            '__EVENTVALIDATION': self.EVENTVALIDATION,
            'txtNome': '',
            'orgao': self.orgao,
            'cargo': self.cargo,
            'situacao': self.situacao,
            'txtDe': '',
            'txtAte': '',
            'hdInicio': str(self.hdInicio) if self.hdInicio > -1 else '',
            'hdFinal': str(self.hdFinal) if self.hdFinal > -1 else '',
            'hdPaginaAtual': str(self.hdPaginalAtual) if self.hdPaginalAtual > 0 else '',
            'hdTotal': str(self.hdTotal) if self.hdTotal > -1 else '',
            '__ASYNCPOST': 'true'
        }
        if self.STARTED:
            parameters.update({'txtPagina': self.txtPagina})
        else:
            parameters.update({'btnExibirRelatorio': 'Pesquisar'})
        r = requests.post(self.URL, data=parameters, headers=self.HEADERS)
        self.PAGE = r.text

    def has_next(self) -> bool:
        return self.hdPaginalAtual != self.hdTotal
